apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: testv1
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/Pyshios/testv1.git
